[project]
name = "morgul-bridge"
version = "0.1.0"
description = "Pythonic wrapper around LLDB's SB API"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/morgul"]
